name: Run Tests and Close PR on Failure

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and run tests
        run: ./gradlew test

  close-pr-on-failure:
    runs-on: ubuntu-latest
    needs: test
    if: failure()

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
    
      - name: Close PR on failure
        run: gh pr close ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
